-dontnote
-dontwarn
-dontshrink
-dontoptimize

-keeppackagenames

-keepattributes Signature,InnerClasses,SourceFile,LineNumberTable
-keepnames class com.eqtechnologic.eqube.mi.activities.invokeopcua.**

-keep class com.eqtechnologic.eqube.mi.activities.invokeopcua.bean.**{
	*;
}

-keep class com.eqtechnologic.eqube.mi.activities.invokeopcua.**{
	public *;
}
