-dontnote
-dontwarn
-dontshrink
-dontoptimize

-keeppackagenames

-keepattributes Signature,InnerClasses,SourceFile,LineNumberTable
-keepnames class com.eqtechnologic.eqube.mi.activities.writetoopcua.*

-keep class com.eqtechnologic.eqube.mi.activities.writetoopcua.*{
	public *;
}
