-keepclassmembers class * {
    public <init>();
    public <fields>;
    public <methods>;
}
-keep class com.eqtechnologic.eqube.mi.activities.writetoopcua.eQWriteToOPCUAExecutor { *; }
-keep class com.eqtechnologic.eqube.mi.activities.writetoopcua.eQWriteToOPCUAErrorCodes { *; }
