-keepclassmembers class * {
    @org.springframework.beans.factory.annotation.Autowired *;
    @org.springframework.beans.factory.annotation.Value *;
}
-keep class com.eqtechnologic.eqube.mi.activities.writetoopcua.bean.** { *; }
