<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"> 

    <modelVersion>4.0.0</modelVersion> 

    <groupId>com.eqtechnologic.eqube.mi.activity</groupId> 

    <artifactId>filezip-runtime</artifactId> 

    <parent> 
        <groupId>com.eqtechnologic.eqube.mi.activity</groupId> 
        <artifactId>filezip-activity</artifactId> 
        <version>8.1.0.0.13</version> 
    </parent> 

    <properties> 
        <!-- Add main.basedir in all pom files under MIActivities, used in px to rem --> 
        <main.basedir>${project.parent.parent.parent.basedir}</main.basedir> 
    </properties> 

    <dependencies> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.mi.activity</groupId> 
            <artifactId>filezip-common</artifactId> 
            <version>${project.version}</version> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.utils</groupId> 
            <artifactId>filehelper</artifactId> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.adminconsole</groupId> 
            <artifactId>dlp-service</artifactId> 
            <version>${adminconsole.version}</version> 
            <classifier>${jarClassifier}</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.connectionManagement</groupId> 
            <artifactId>connection_management_application</artifactId> 
            <classifier>signed</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.process</groupId> 
            <artifactId>processmanagement</artifactId> 
            <classifier>${jarClassifier}</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.process</groupId> 
            <artifactId>job-orchestrator</artifactId> 
            <classifier>${jarClassifier}</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <artifactId>filesystem-connection-service</artifactId> 
            <groupId>com.eqtechnologic.eqube.mi</groupId> 
            <version>${project.version}</version> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.adminconsole</groupId> 
            <artifactId>componentframework-service</artifactId> 
            <version>${adminconsole.version}</version> 
            <classifier>${jarClassifier}</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.process</groupId> 
            <artifactId>pem-enums</artifactId> 
            <classifier>${jarClassifier}</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.adminconsole</groupId> 
            <artifactId>connection</artifactId> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
            <classifier>${jarClassifier}</classifier> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.adminconsole</groupId> 
            <artifactId>micommonbeans</artifactId> 
            <classifier>${jarClassifier}</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.adminconsole</groupId> 
            <artifactId>adminconsoleutil</artifactId> 
            <version>${adminconsole.version}</version> 
            <classifier>${jarClassifier}</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>org.apache.commons</groupId> 
            <artifactId>commons-lang3</artifactId> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.process</groupId> 
            <artifactId>pem-beans</artifactId> 
            <version>${pem.version}</version> 
            <classifier>${jarClassifier}</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.adapter</groupId> 
            <artifactId>adapter-api</artifactId> 
            <classifier>signed</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.dlp</groupId> 
            <artifactId>dlp-api</artifactId> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.properties</groupId> 
            <artifactId>property-common-api</artifactId> 
            <classifier>signed</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.adapternextgen</groupId> 
            <artifactId>plugin</artifactId> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
            <classifier>signed</classifier> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.adapter.service</groupId> 
            <artifactId>adapter-service-client</artifactId> 
            <classifier>signed</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.mi</groupId> 
            <artifactId>mi-adapter-service-util</artifactId> 
            <version>${project.version}</version> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.applicationconnection</groupId> 
            <artifactId>connectionconfiguration-service</artifactId> 
            <classifier>signed</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.utils</groupId> 
            <artifactId>logging</artifactId> 
            <classifier>signed</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.adapter</groupId> 
            <artifactId>meta</artifactId> 
            <classifier>signed</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.utils</groupId> 
            <artifactId>exception</artifactId> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.adapternextgen</groupId> 
            <artifactId>pluginclient</artifactId> 
            <classifier>signed</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.soa</groupId> 
            <artifactId>servicemanagement</artifactId> 
            <classifier>signed</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.process</groupId> 
            <artifactId>activitymanagement-service-common</artifactId> 
            <version>${pem.version}</version> 
            <classifier>${jarClassifier}</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.connectors.util</groupId> 
            <artifactId>commons-connector-utils</artifactId> 
            <classifier>signed</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>org.apache.logging.log4j</groupId> 
            <artifactId>log4j-api</artifactId> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.soa</groupId> 
            <artifactId>notification-service</artifactId> 
            <classifier>signed</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>org.aspectj</groupId> 
            <artifactId>aspectjrt</artifactId> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.soa</groupId> 
            <artifactId>cachelayer-service</artifactId> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
            <classifier>signed</classifier> 
        </dependency> 
        <dependency> 
            <groupId>jakarta.xml.soap</groupId> 
            <artifactId>jakarta.xml.soap-api</artifactId> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
    </dependencies> 
    <build> 
        <plugins> 
            <plugin> 
                <groupId>com.github.wvengen</groupId> 
                <artifactId>proguard-maven-plugin</artifactId> 
            </plugin> 
            <plugin> 
                <groupId>org.apache.maven.plugins</groupId> 
                <artifactId>maven-jarsigner-plugin</artifactId> 
            </plugin> 
            <plugin> 
                <artifactId>maven-assembly-plugin</artifactId> 
            </plugin> 
        </plugins> 
    </build> 
</project>
