/**
* Created by Lovish.
*/
define({
    "root": {
        "writetoopcua.displayName": "Write To OPC UA",
        "writetoopcua.description": "Write To OPC UA activity.",
        "TransportNameVariable": "Transport Name as Variable",
        "TransportName": "Transport Name",
        "SelectTransport": "Select Transport",
        "Operation": "Operation",
        "DataChangeWrite": "Data Change Write",
        "CallMethod": "Method Call",
        "ExecutionMode": "Execution Mode",
        "Parallel": "Parallel",
        "ParallelHelp": "Executes OPC UA write operations in parallel.",
        "Sequential": "Sequential",
        "SequentialHelp": "Executes OPC UA write operations in sequential order.",
        "DataChangeName": "Data Change Name",
        "NodeId": "Node ID",
        "SampleValue": "Sample Value",
        "NewValue": "New Value",
        "Action": "Action",
        "MethodName": "Method Name",
        "InputParameters": "Input Parameters",
        "OutputValue": "Output Value",
        "AddMethodCall": "Add Method Call:",
        "ParameterName": "Parameter Name",
        "DataType": "Data Type",
        "Value": "Value",
        "SelectMethod": "Select Method",
        "SelectDataChange": "Select Data Change",
        "Add": "Add",
        "Delete": "Delete",
        "Search": "Search",
        "Refresh": "Refresh",
        "Create": "Create",
        "Open": "Open",
        "Save": "Save",
        "Cancel": "Cancel",
        "writetoopcua.outputSuccessfulWriteItems": "Successful Write items",
        "writetoopcua.outputFailedWriteItems": "Failed Write items",
        "writetoopcua.outputSkippedWriteItems": "Skipped Write items",
        "writetoopcua.selTransport": "Please select a Transport Name.",
        "writetoopcua.emptyDataChangeWrite": "At least one Data Change Write configuration is required.",
        "writetoopcua.emptyCallMethod": "At least one Method Call configuration is required.",
        "writetoopcua.emptyDataChangeName": "Please select a Data Change Name.",
        "writetoopcua.emptyNewValue": "Please specify New Value.",
        "writetoopcua.emptyMethodName": "Please select a Method Name.",
        "writetoopcua.emptyParameterValue": "Please specify value(s) in Input Parameters.",
        "writetoopcua.transportNotFound": "Unable to fetch Transport because of an error.",
        "writetoopcua.transportFrameworkError_transport": "Unable to validate Transport because of an error.",
        "TransportTestFailed": "Server is unavailable. Value suggestions cannot be provided.",
        "NodeDetails": "Node Details",
        "NodeName": "Node Name",
        "ObjectNodeId": "Object Node ID",
        "DataTypeName": "Data Type Name",
        "DataTypeNodeId": "Data Type Node ID",
        "MethodNameLabel": "Method Name",
        "NodeIdLabel": "Node ID",
        "SampleValueLabel": "Sample Value",
        "Copy": "Copy",
        "Copied": "Copied",
        "ViewInputParameters": "View input parameters"
    }
});
