<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>deviceconnector-connection</artifactId>
        <groupId>com.eqtechnologic.eqube.mi</groupId>
        <version>8.1.0.0.13</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>deviceconnector-connection-serviceimpl</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.eqtechnologic.eqube.adminconsole</groupId>
            <artifactId>commonconnection-service</artifactId>
            <classifier>${jarClassifier}</classifier>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.eqtechnologic.eqube.platform.applicationconnection</groupId>
            <artifactId>connectionconfigurationclient-service</artifactId>
            <classifier>signed</classifier>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.eqtechnologic.eqube.adminconsole</groupId>
            <artifactId>componentframework-service</artifactId>
            <version>${adminconsole.version}</version>
            <classifier>${jarClassifier}</classifier>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.eqtechnologic.eqube.mi</groupId>
            <artifactId>deviceconnector-connection-service</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.eqtechnologic.eqube.platform.utils</groupId>
            <artifactId>logging</artifactId>
            <classifier>signed</classifier>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.eqtechnologic.eqube.platform.utils</groupId>
            <artifactId>exception</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.eqtechnologic.eqube.platform.soa</groupId>
            <artifactId>servicemanagement</artifactId>
            <classifier>signed</classifier>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>com.github.wvengen</groupId>
                <artifactId>proguard-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
