-dontnote 
-dontwarn 
-dontshrink 
-dontoptimize 

-keeppackagenames 

-keepattributes Signature,Exceptions,InnerClasses,SourceFile,LineNumberTable,*Annotation* 

-keep class com.eqtechnologic.eqube.mi.componentservices.deviceconnectorconnection.**{ 
    public *; 
}
