/**
 * Created by Lovish.
 */
define({
    "root": {
        "invokeopcua.displayName": "Invoke OPC UA",
        "invokeopcua.description": "Invoke OPC UA activity.",
        "Connection": "Connection",
        "SelectConnection": "Select Connection",
        "RefreshConnection": "Refresh connection",
        "ConnectionsRefreshed": "Connections refreshed successfully.",
        "InvalidConnection": "Please select a valid OPC UA connection.",
        "InvalidOPCUAConnection": "Please select a valid OPC UA connection.",
        "ConnectionTestFailed": "Server is unavailable. Value suggestions cannot be provided.",
        "invokeopcua.selConnection": "Please select a Connection.",
        "invokeopcua.invalidConnection": "Select a valid OPC UA connection.",
        "invokeopcua.connectionNotFound": "Unable to fetch Connection because of an error.",
        "invokeopcua.connectionFrameworkError_connection": "Unable to validate Connection because of an error.",
        "Operation": "Operation",
        "DataChangeWrite": "Data Change Write",
        "CallMethod": "Method Call",
        "ExecutionMode": "Execution Mode",
        "Parallel": "Parallel",
        "ParallelHelp": "Executes OPC UA write operations in parallel.",
        "Sequential": "Sequential",
        "SequentialHelp": "Executes OPC UA write operations in sequential order.",
        "DataChangeName": "Data Change Name",
        "NodeId": "Node ID",
        "SampleValue": "Sample Value",
        "NewValue": "New Value",
        "Action": "Action",
        "Browse": "Browse",
        "BrowseAddressSpace": "Browse Address Space",
        "SelectNode": "Select Node",
        "SelectMethod": "Select Method",
        "Node": "Node",
        "NodeClass": "Node Class",
        "SearchAddressSpace": "Search Address Space",
        "LoadingAddressSpace": "Loading address space...",
        "ErrorFetchingAddressSpace": "Error while fetching address space.",
        "ErrorFetchingChildren": "Error while fetching child nodes.",
        "ErrorFetchingMethodParams": "Error while fetching method parameters.",
        "MethodName": "Method Name",
        "InputParameters": "Input Parameters",
        "OutputValue": "Output Value",
        "AddMethodCall": "Add Method Call:",
        "ParameterName": "Parameter Name",
        "DataType": "Data Type",
        "Value": "Value",
        "SelectDataChange": "Select Data Change",
        "Add": "Add",
        "Delete": "Delete",
        "Search": "Search",
        "Refresh": "Refresh",
        "Create": "Create",
        "Open": "Open",
        "Save": "Save",
        "Cancel": "Cancel",
        "invokeopcua.outputSuccessfulWriteItems": "Successful Write items",
        "invokeopcua.outputFailedWriteItems": "Failed Write items",
        "invokeopcua.outputSkippedWriteItems": "Skipped Write items",
        "invokeopcua.emptyDataChangeWrite": "At least one Data Change Write configuration is required.",
        "invokeopcua.emptyCallMethod": "At least one Method Call configuration is required.",
        "invokeopcua.emptyDataChangeName": "Please select a Data Change Name.",
        "invokeopcua.emptyNewValue": "Please specify New Value.",
        "invokeopcua.emptyMethodName": "Please select a Method Name.",
        "invokeopcua.emptyParameterValue": "Please specify value(s) in Input Parameters.",
        "NodeDetails": "Node Details",
        "NodeName": "Node Name",
        "ObjectNodeId": "Object Node ID",
        "DataTypeName": "Data Type Name",
        "DataTypeNodeId": "Data Type Node ID",
        "MethodNameLabel": "Method Name",
        "NodeIdLabel": "Node ID",
        "SampleValueLabel": "Sample Value",
        "Copy": "Copy",
        "Copied": "Copied",
        "ViewInputParameters": "View input parameters"
    }
});
