<project xmlns="http://maven.apache.org/POM/4.0.0" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"> 

    <modelVersion>4.0.0</modelVersion> 
    <artifactId>filezip-activity</artifactId> 
    <groupId>com.eqtechnologic.eqube.mi.activity</groupId> 
    <packaging>pom</packaging> 
    <parent> 
        <groupId>com.eqtechnologic.eqube.mi.activity</groupId> 
        <version>8.1.0.0.13</version> 
        <artifactId>activities</artifactId> 
    </parent> 

    <properties> 
        <!-- Add main.basedir in all pom files under MIActivities, used in px to rem --> 
        <main.basedir>${project.parent.parent.basedir}</main.basedir> 
    </properties> 
    <dependencies> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.soa</groupId> 
            <artifactId>soa-aspects</artifactId> 
            <classifier>signed</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.platform.soa</groupId> 
            <artifactId>methodauthorization-service</artifactId> 
            <classifier>signed</classifier> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
        <dependency> 
            <groupId>com.eqtechnologic.eqube.mi</groupId> 
            <artifactId>filter-service</artifactId> 
            <version>${project.version}</version> 
            <exclusions> 
                <exclusion> 
                    <groupId>*</groupId> 
                    <artifactId>*</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency> 
    </dependencies> 
    <build> 
        <plugins> 
            <plugin> 
                <groupId>org.apache.maven.plugins</groupId> 
                <artifactId>maven-jarsigner-plugin</artifactId> 
            </plugin> 
            <plugin> 
                <groupId>org.codehaus.mojo</groupId> 
                <artifactId>aspectj-maven-plugin</artifactId> 
                <configuration> 
                    <aspectLibraries> 
                        <aspectLibrary> 
                            <groupId>com.eqtechnologic.eqube.platform.soa</groupId> 
                            <artifactId>soa-aspects</artifactId> 
                            <classifier>signed</classifier> 
                        </aspectLibrary> 
                    </aspectLibraries> 
                </configuration> 
            </plugin> 
        </plugins> 
    </build> 
    <modules> 
        <module>FileZip-Common</module> 
        <module>FileZip-Designer</module> 
        <module>FileZip-Runtime</module> 
        <module>FileZip-Bundle</module> 
    </modules> 
</project>
