-dontnote 
-dontwarn 
-dontshrink 
-dontoptimize 

-keeppackagenames 

-keepattributes Signature,InnerClasses,SourceFile,LineNumberTable 
-keepnames class com.eqtechnologic.eqube.mi.activities.filezip.** 



-keep class com.eqtechnologic.eqube.mi.activities.filezip.FileZipComponentRestController{ 
public *; 
}
