-dontnote -dontwarn -dontshrink -dontoptimize
-keeppackagenames
-keepattributes Signature,InnerClasses,SourceFile,LineNumberTable
-keepnames class com.eqtechnologic.eqube.mi.activities.filezip.**
-keep class com.eqtechnologic.eqube.mi.activities.filezip.FileZipConstants{ public *;}
-keep class com.eqtechnologic.eqube.mi.activities.filezip.FileZipErrorCodes{ public *;}
-keep class com.eqtechnologic.eqube.mi.activities.filezip.FileZipLicense{ public *;}
-keep class com.eqtechnologic.eqube.mi.activities.filezip.bean.{ *;}
-keep class com.eqtechnologic.eqube.mi.activities.filezip.helper.**{ public *;}
-keep class com.eqtechnologic.eqube.mi.activities.filezip.FileZipValidator{ public *;}
-keep class com.eqtechnologic.eqube.mi.activities.filezip.FileZipComponentService{ public *;}
-keep class com.eqtechnologic.eqube.mi.activities.filezip.FileZipConfiguration{ public *;}
-keep class com.eqtechnologic.eqube.mi.activities.filezip.exception.{ public *;}
